### ISSUE TITLE
AlternateRows and sort_col_at_start

### ISSUE THREAD

**Issue by thenning** [koalyptus/TableFilter#365]
When using the two in conjunction, the alternate rows don't wind up getting reapplied so rows are mixed up. I've tried doing a work around where I call the sortColumnIndex function off the extension works in developer tools console, but not when ran from code. Doesn't seem like the initial sort is triggering whatever event fixes the alternate rows.

**Comment by koalyptus** [comment]
Thanks @thenning for spotting this out, indeed zebra rows are off. 
The column sorting capability is an extension loaded asynchronously at start-up, that's why your logic works in the console when the extension is already loaded and not 'from the code'. To ensure the sort extension is loaded you could hook into the `on_sort_loaded` callback (https://github.com/koalyptus/TableFilter/wiki/3.1-Sort) or take advantage of TableFilter events, so while waiting for a fix try this:
```javascript
    var tf = new TableFilter('table-id', yourConfig);
    tf.emitter.on(['sort-initialized'], function(tf) {
        // AlternateRows listens to event below
        tf.emitter.emit('column-sorted');
    });
    tf.init();
```

**Comment by koalyptus** [comment]
Should now be fixed starting from v.0.4.22.
