### ISSUE TITLE
Error when table is empty or with just one row

### ISSUE THREAD

**Issue by jerefrer** [koalyptus/TableFilter#380]
Hi there,

If my table is empty or with just one row, I get the following error.
Starting from 2 rows everything just works perfectly.

![error](http://i.imgur.com/i8To44T.png)

Any idea why ?

**Comment by koalyptus** [comment]
TableFilter  requires at least 1 row in order to know the number of columns to generate a filter for each column.
If you have only 1 row then you need to supply the numeric argument to the constructor : new TableFilter('my-table-id', 0, myConfig);
Refer to koalyptus.github.io/TableFilter/no-headers.html

**Comment by koalyptus** [comment]
Finally realised, previous refactoring work introduced a regression at instantiation when the HTML table contains only 1 row. This is now covered by tests.
Starting from v0.4.31 when the HTML table contains 1 row, `TableFilter` will instantiate without javascript exception.
It will continue to throw an error when the HTML table has 0 rows.
Tell me how it goes.

**Comment by jerefrer** [comment]
@koalyptus Works like a charm after upgrading. Awesome support as always. Thanks ! :+1:

**Comment by koalyptus** [comment]
Hey @jerefrer, in v0.4.31 I accidentally committed the unminified files in the dist folder as per 381#issuecomment-270389699. Please use v0.4.32 instead.
Cheers
