### ISSUE TITLE
data-tf-sortkey not working on inputs

### ISSUE THREAD

**Issue by IObregon** [koalyptus/TableFilter#432]
Hi,

I have a table which contains some normal td's with their values and sorting works perfectly but I have two cells where I have one input in each and sorting does not work.

I found in this wiki [Sort](https://github.com/koalyptus/TableFilter/wiki/3.1-Sort) that it was posible to use `data-tf-sortKey` to especify what is the value to sort by. If I put that data attribute in the <input>, the sorting goes crazy. However, if I put it to the <td> it works correctly. Is this how it should to work?

Once again thanks for this big help for the comunnity.

**Comment by koalyptus** [comment]
Yes, this is how it should work, the `data-tf-sortKey` attribute containing the cell value to sort by has to be specified on each `td` of a column. Check this demo out to see in action: http://koalyptus.github.io/TableFilter/filter-images.html .
Alternatively instead of using the `data` attribute, you could programmatically define your sorter function for the desired column as explained in this demo:
http://koalyptus.github.io/TableFilter/sort-custom-type.html

**Comment by IObregon** [comment]
Ok, if that is the desired behavior.

Thanks for your fast answer.
