### ISSUE TITLE
Sorting Problem with numbers

### ISSUE THREAD

**Issue by c0rny** [koalyptus/TableFilter#478]
Hello everyone

First of all, thanks for that great Table Filter. Everything work great exept one Thing:
There are about 700 rows in my table. That column that contains only numbers or "empty fields" (null) will not be sorted correctly. 
Example table (only column with these numbers) Looks like:
-144
-20
_null
null_
0
_null
null_
1
2
3
Zero should be at the last Position with negativ numbers or at the first Position followed by positiv numbers.

Maybe anybody else with this Problem?

Thanks and regards
Patrick

**Comment by koalyptus** [comment]
@c0rny be aware `null` or empty values default to zero in numeric columns as they cannot be converted to a number type, that's why they appear next to the zero value. If you need to make those values appear in a arbitrary position I advise you to implement a custom sorter for that column, refer to this demo:
http://koalyptus.github.io/TableFilter/sort-custom-type.html

**Comment by koalyptus** [comment]
I just posted this codepen to give an idea of what I mean: https://codepen.io/koalyptus/pen/PjLVdO

**Comment by c0rny** [comment]
@koalyptus You have saved my life! Thank you so much! :)
