### ISSUE TITLE
How to deal with empty dates entries

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#484]
What is the recommended way of dealing with entries in a table filter table in a column with col type of date where there is no data?

We're using getTableData (and similar methods) to return data to a function to create a csv download of filtered data.  We're parsing the data returned to add double quotes around each entry so that line breaks, commas etc are dealt with correctly when the csv is imported into excel etc.
We also do a search and replace to exchange any " in the field with a ' so as not to break the csv field delimiters.
Since we added "col_types" to the tf definition (so that sorting and filtering works better) the dates are returned as objects by getTableData and returns "invalid dates" if there is no entry in that field (which we represent with a "-"  ) or if there is no time returned with the date.  We don't want to add a time to a "date of birth" field and we don't always have an "period end" date for every "period start" date we record.
Can you let us know the best way of using TF in these situations please?

**Comment by koalyptus** [comment]
In your case, since you are constructing a string for csv export, I rather use the `getValues`, `getFilteredValues` helpers which return the cell values as strings:
- http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html#instance-method-getValues
- http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html#instance-method-getFilteredValues
- http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html#instance-method-getFilteredColumnValues
- http://koalyptus.github.io/TableFilter/docs/class/src/tablefilter.js~TableFilter.html#instance-method-getVisibleColumnValues

So your formatted dates would be returned as such along with your empty dates represented by a `-`.

**Comment by cjohnsonuk** [comment]
That works great!  Thank you! :-)
