### ISSUE TITLE
local_storage

### ISSUE THREAD

**Issue by WaiPang** [koalyptus/TableFilter#491]
I find the local_storage feature to be very useful for caching the filter criteria. 
I wonder whether this can be made global?

I have table filters generated every day for the performance testing. Sometimes I find that I want to have the same filter criteria for all tables. So that I can quickly go through all the historical pages with the same search criteria. 

If this is not possible - would you recommend doing the following:

var tf = new TableFilter(); 
if (file exists && read the file on webserver ){
 tf.setFilterValue(2, "populate criteria specified from the file");
 tf.filter();
}

**Comment by koalyptus** [comment]
There is no notion of global caching, filter criteria are stored on a per table-id and URL path basis, the key of a store looks like this:
```javascript
{"key":"TF_{table-id}","path":"{url-path}l"}
```
as per https://github.com/koalyptus/TableFilter/blob/master/src/modules/storage.js#L142.

The javascript here runs on the browser, as a result you cannot access the file system of the server...
If you have control over your application, you might consider url hash persistence (`hash`) instead of local storage. If your tables are in located in different screens/pages/routes you might consider preserving the URL hash in your links so that filter criteria are preserved across pages.

**Comment by WaiPang** [comment]
Thanks for the prompt reply.

By URL hash does you mean something like

www.mywebsite.com/mypage1.html?mytableid#col1=value1#col2=value2<http://www.mywebsite.com/mypage1.html?mytableid#col1=value1#col2=value2>
www.mywebsite.com/mypage2.html?mytableid#col1=value1#col2=value2<http://www.mywebsite.com/mypage2.html?mytableid#col1=value1#col2=value2>

to automatically set the same criteria values across different pages?

I found the documents for url hash

https://github.com/koalyptus/TableFilter/wiki/1.17-State

I guess I need use the hash.js and to set the following

var tfConfig = { state: { types: ['hash'] };

What parameters do I actually use on the url to achieve this?

BTW: I am on holiday next week – if I get some help with the url hash in the next 9 hours I will try out immediately ☺

**Comment by koalyptus** [comment]
You don't need to construct the hash yourself, use javascript's location.hash to access the hash fragment of the url and append it programmatically to your links. 
You can shorten the setting value to var config = { state: true }; as it defaults to hash.

**Comment by WaiPang** [comment]
Is it possible to have both hash and local_storage?
