### ISSUE TITLE
ezEditTable dependency not found with TableFilter v0.5.41

### ISSUE THREAD

**Issue by mmaction** [koalyptus/TableFilter#512]
I'm using ezEditTable extension v2.3 which worked with TableFilter v0.4.40.
For solving a problem i upgraded to TableFilter v0.5.41. Now i'm getting the following error in FF50, IE11:
"Failed to instantiate EditTable object. "ezEditTable" dependency not found.

What am i missing? Did something change regarding instanciation tableFilter with extensions?

The main problem i try to solve is the following:
We use a table with a minimum row size of 12, so we populate 12 empty rows if there are no records (and adjust rowcounter etc. by javascript). This all works fine. But if a user sorts the table (e.g. 2 records and 10 empty rows) the empty rows are considered as well so that the table displays the 10 empty rows first and then the 2 records.
-> Is there a workaround for this scenario?

I removed the populating of the empty rows but than i get the error as described (ezEditTable dependency not found).

Here is the TableFilter setup any advise is very appreciated:

        /* Setup table filtering */
      	tf = new TableFilter('tblRemoteUnits',
      	{
      		/* filters behaviour */
      		base_path: '../tablefilter/',
      		col_widths: [ "38px", "142px", "340px", "81px", "188px", null, null, null ],
      		col_0: "none",
      		col_3: "select",
            col_5: "none",
            col_6: "none",
            col_7: "none",
      		filters_row_index: 1,
      		auto_filter: true,
      		auto_filter_delay: 0,
      		remember_grid_values: true,
      		alternate_rows: true,
      		mark_active_columns: true,
      		watermark: "search...",
	      	on_after_refresh_counter: adjustCounter,

      		/* drop-down filter */
      		clear_filter_text: "All",

      		/* grid layout */
      		grid_layout: true,
      		grid_height: '228px',
      		grid_width: '778px',

      		/* status bar, rows counter, help instructions, reset button */
      		status_bar: true,
      		rows_counter: true,
      		rows_counter_text: 'Number of Entries: ',
      		btn_reset: true,
      		help_instructions: false,
      
            /* persistence */
      		state: {
      			types:['local_storage'],
      			filters: true,
      			sort: true
      		},	

      		/* extensions*/
    		extensions:
      		[
            	{
            	  name: 'sort',
      			  types: ['Number', 'String', 'ipaddress', 'String', 'String', 'none', 'none', 'none' ],
        	    },
      			{
      			  name: 'advancedGrid',
       			  vendor_path: '../ezEditTable/',
	      	      selection_model: 'multiple',
      			  on_after_selected_row: afterRowSelected,
       	          on_selection_initialized: onSelectionInitialized,
      			  nb_rows_per_page: 11,
      			}
            ],

      	});
      	tf.init();

**Comment by koalyptus** [comment]
Hi @mmaction,
1. since v0.4.40 there are no changes in the way extensions are instantiated. In your scenario, if you remove the empty rows with v0.4.40 you should get the same error. This error is thrown when ezEditTable fails to instantiate (the message itself can be misleading), my guess is that ezEditTable cannot instantiate correctly when there are no rows.
2. Since 0.4.40 there have been changes to the sort functionality, empty cells are now appearing consistently at the top (asc sorting) or at the bottom (desc sorting) as opposed to previously where they could have appeared in the middle in large datasets. Now, in your case you may always want to place those rows at the bottom, whatever is the sorting direction. My advice is to implement a custom sorter to do so, check this [demo](http://koalyptus.github.io/TableFilter/sort-custom-type.html) out and this codepen I created for another issue: https://codepen.io/koalyptus/pen/PjLVdO. Those examples should give an idea of how to implement a custom sorter for each column type (`number`, `string`, `ipaddress`)
3. I noticed some of your configuration settings are no longer supported:
- `remember_grid_values: true` is replaced by `state`, can therefore be removed
- `grid_layout` is no longer a flat structure:
```javascript
grid_layout: {
  height: '228px',
  width: '778px'
};
```
- same for `rows_counter`:
```javascript
rows_counter: {
  text: 'Number of Entries: ',
  on_after_refresh_counter: adjustCounter,
};
```
Also remove trailing `,` in last property of an object, ie: 
`nb_rows_per_page: 11,` -> `nb_rows_per_page: 11`
`],` -> `]`
some browsers can be sensitive to that (old IE)

I hope this helps, let me know.
