### ISSUE TITLE
Colvisibility

### ISSUE THREAD

**Issue by Ileouleyuki** [koalyptus/TableFilter#520]
Hye,
Do you know if it is possible to get an array of the column hide or show ?  I don't find the issue in the doc. 
I want to save the user sélection to load it every time.
Thanks for your answer and great job.
Jules

**Comment by koalyptus** [comment]
Tx @Ileouleyuki,
you can use the `state` option to do so, check this demo out:
http://koalyptus.github.io/TableFilter/persistence.html

Otherwise check the full `ColsVisibility` API here:
http://koalyptus.github.io/TableFilter/columns-visibility.html
and configuration options here:
https://github.com/koalyptus/TableFilter/wiki/3.4-Columns-visibility
Also have a look to the columns visibility demo:
http://koalyptus.github.io/TableFilter/columns-visibility.html

**Comment by Ileouleyuki** [comment]
Great, Wonderful, ... :)
So i use the, i get it with `tf.extension('colsVisibility').hiddenCols` ... easy :)
It give me what i want,: an array with the hiddenCols.
Thanks for your help koalyptus
You can close the issue
