### ISSUE TITLE
Issue when there's a table tag inside a cell

### ISSUE THREAD

**Issue by MathieuThiry** [koalyptus/TableFilter#558]
Hello, thanks again for all of your work !

I updated from an old version (< 0.3) to 0.6.15. Since tablefilter stop running when there's a table tag inside a cell.

Example : https://codepen.io/mathieuthiry/pen/rpqopY

Do you know why ?

**Comment by koalyptus** [comment]
Tx for pointing this out, it looks like a regression to me. Try to remove the thead and tbody tags from the table element inside the cell and tell me how it goes. I have a theory but didn't have a chance to come back to this project yet. A lot of refactoring and a lot more of unit tests were added since older versions, but this particular scenario is not covered by test. Any other tag with text as child node should work.

**Comment by MathieuThiry** [comment]
It works only when there's no child node in table.

What're you thinking ?

**Comment by koalyptus** [comment]
What do you mean by no child node in table? Have you tried
<table>
<tr><td>foo</td></tr>
</table>
Inside the cell? That's what I meant.
And this should work inside a cell :
<div><span>foo</span></div>

**Comment by MathieuThiry** [comment]
Doesn't work either. :(

**Comment by koalyptus** [comment]
Tx for checking @MathieuThiry, I will try to come with a fix in the next release(s), hopefully.

**Comment by MathieuThiry** [comment]
No, thanks to you, tableFilter is truly amazing!

I wonder if is it normal that getWorkingRows() returns tr descendants of td ?

Good luck !

**Comment by koalyptus** [comment]
Tx @MathieuThiry, exactly right the query in `getWorkingRows()` was too loose and included any row even those belonging to nested tables.
Starting from `v.0.6.16` this should be fixed, let me know how it goes.

**Comment by MathieuThiry** [comment]
It works as expected, great!
