### ISSUE TITLE
Drop-Down Checklist-Filter like in Excel?

### ISSUE THREAD

**Issue by Cut7er** [koalyptus/TableFilter#582]
Hello,

I was wondering if there is a way to implement the checklist or multiple filter into a drop-down menu?

When there are multiple filterable options, the filter header looks really big and destroys my filter layout massively. So it would be enough to take a dropdown-filter with the option of multiple selections. I tried all of your combinations and didn't found the right one.

![table_filter](https://user-images.githubusercontent.com/38125552/38407525-24fff85e-397a-11e8-8f19-f878c09d340e.PNG)

Edit: what I found impossible to do as well was to change the background color from grey to light blue for the alternating color property. The alternating rows are working, but it stays grey, no matter how often I change every single background color in the CSS Default theme. I changed them in the filtergrid.css as well. Do you have any idea where the problem could be?

Edit2: Actually I can just use the specified methods from you like `btn_reset: true, paging_length: 50`, etc. Every change in .css or the text in the .js files in the TableFilter directory have no effect. Do you know about this issue and can explain it? 

Best regards

**Comment by koalyptus** [comment]
Hi @Cut7er,
Most of the visual features and behaviours are driven by configuration settings:
- to change the alternating rows appearance you can use `even_row_css_class` and `odd_row_css_class` options instead of editing the widget's stylesheet. There are many ways to customise the table appearance, refer to this codepen https://codepen.io/koalyptus/pen/pLqRpL to have an idea
- if you want to edit the 'javascript' or 'stylesheets' yourself please follow the README [development section](https://github.com/koalyptus/TableFilter#development)

cheers
