### ISSUE TITLE
Prevent input field from loading in specific column

### ISSUE THREAD

**Issue by ghost** [koalyptus/TableFilter#829]
Hello there,

I took a look at the <a href="https://www.tablefilter.com/0-configuration.html">basic</a> 0 configuration example table and wondered if it is possible to either exclude certain columns from having an input field or if it is possible to turn it invisible by other means.
I can make the filed invisible using "style="visibility: collapse;"" on the parent <td> element via the dev console, but since the <td> element has no class, I am not able to make the change persistent. Does anyone know if there is a fix for my problem?

**Comment by cjohnsonuk** [comment]
You can either use a filter type of none as demonstrated here: https://www.tablefilter.com/filter-types.html
to turn off the column filter for that column

Or you can hide the column visibility plugin as demonstrated here https://www.tablefilter.com/columns-visibility.html
to hide the columns you don't want to see

HTH

**Comment by neo-sodom** [comment]
Thanks for the reply. While the <code>col_7: 'none',</code> makes the input field invisible which is great and helpful, I still need to edit the <code>td</code> parent element somehow. Right now the input cell looks like that:<br><br>

`<td><input id="flt7_demo" type="hidden" ct="7" class="flt"></td>`

but it should look like that:

`<td style="background-color: white;"><input id="flt7_demo" type="hidden" ct="7" class="flt"></td>`

I will close the issue nonetheless, since it does not relate to TableFilter solely anymore.
